### ISSUE TITLE
Write docs

### ISSUE THREAD

**Issue by per-gron** [per-gron/overman#39]
# Top level
- What it is. [… if this sounds just like Mocha to you, it's because it _is_ very similar to Mocha.] For node only.
- Features
- Usage
  - Installation
  - Write a test (including how to do assertions and where to place the file)
  - Run the test
- Contributing
  - Make sure tests and the linter passes
  - If applicable update documentation
# Sub-pages
- [x] Writing tests using the BDD interface: #43
- [ ] Running tests with the CLI
- [x] Running tests with the Javascript API #56 
- [x] How to interpret error messages
- [ ] Tools for improving error reporting
- [x] Writing custom reporters using the Reporter API: #44
- [x] Writing custom interfaces with the Interface API: #46
- [ ] Differences compared to Mocha
  - Tests run in separate process (consequences for speed, before/after hooks, communication between tests and reporters)
  - After hooks are not executed on timeout
  - node only
  - Mention that there are probably unnecessary differences, they should be fixed
- [ ] Internal architecture
